In [1]:
# basically how to import the numpy and the creation of the array
import numpy as np6

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

In [3]:
# the syntax is used to check the version for the numpy
print(np.__version__)

1.24.3


In [4]:
# creating array in the numpy using ndarray function
arr=np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# we can also use a tupe for the creation of the numpy array
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [6]:
# Learning how to create 2d array in numpy
import numpy as np
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [8]:
# creating 3d arrays in numpy
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
# checking the dimensions of the array
a =  np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
# we can simply define the dimesion in array using the ndim method
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print("no. of dimesions",arr.ndim)

[[[[[1 2 3 4 5]]]]]
no. of dimesions 5


In [13]:
# Now learning how to acess the elements of the array
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[2]+arr[3])

1
2
7


In [2]:
# Now acessing the elements of the 2d array
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row',arr[0][1])
print(arr[1,3])
print('Last element from 2nd dim: ', arr[1, -1])

2nd element on 1st row 2
9
Last element from 2nd dim:  10


In [17]:
# Now acessing the elements of the 3d array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [23]:
# Now learning how to slice the elements of the array
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:6])
print(arr[4:])
print(arr[:4])
# negativing slicing of the array
print(arr[-3:-1])
print(arr[1:5:2])

[2 3 4 5 6]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]


In [29]:
# Now learning how to perfomr the slicing the in the 2d arrays
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,0:4])
print(arr[0:2,2])

[6 7 8 9]
[3 8]


In [30]:
# Now learning about the data types in the numpy
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [31]:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [32]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr.dtype)

|S1


In [33]:
# in this example as u can see we are defining the datatypes previously
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [34]:
# astype is a function that is used to create the copy for the array
import numpy as np
arr=np.array([1.1,2.1,3.1])

newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [35]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [36]:
# now dealing with the copy and the view of the array

import numpy as np

arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42

print(x)
print(arr)

[1 2 3 4 5]
[42  2  3  4  5]


In [37]:
# now u will notice that the changes made in view also rflected in the original array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [39]:
# shape is the no. of elements in each dimension of the array
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr.shape)

(1, 1, 1, 1, 4)


In [41]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)

(5,)


In [42]:
# Now applying the sorting function to the array

import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [43]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [44]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [46]:
import numpy as np
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [48]:
# where function is used to search an elemet inside the array
arr=np.array([1,2,3,4,5,4,4])

x=np.where(arr==4)
print(x)
# it will simpy return al the index where 4 is present

(array([3, 5, 6], dtype=int64),)


In [49]:
# Now find the index where the value is even
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])

x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [50]:
# Now fidnid where the vlaues are odd
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [54]:

x = np.searchsorted(arr, 7)

print(x)

6


In [55]:
x=np.searchsorted(arr,6)
print(x)

5


In [57]:
import numpy as np
arr=np.array([6,7,8,9])

x=np.searchsorted(arr,7,side='left')
print(x)

1


In [58]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [63]:
#Create Zeros and ones custom array
a=np.zeros((3,3))
print(a)
# printing by default 2d array
b=np.ones((3,3))
print(b)
# Array of some constant
c=np.full((3,2),5)
print(c)

# how to create an identity matrix
d=np.eye(4)
print(d)

# How to create a random matrix
randomMatrix=np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.6156627  0.95847379 0.93318424]
 [0.92484376 0.93604739 0.71850217]]


In [65]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])

[2 3 4]


In [66]:
# Now changing the elements of the random matrix
randomMatrix[1,1:]=1
print(randomMatrix)

[[0.6156627  0.95847379 0.93318424]
 [0.92484376 1.         1.        ]]


In [67]:
#Datatypes
# we can also change the data type for the array
print(randomMatrix.dtype)

float64


In [73]:
# Mathematical operation using numpy

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print("Sum of the array is",x+y)
print("Difference of two array is",x-y)
# this is how we can perform multiplication
print(x*y)
print(np.multiply(x,y))
# we can also use add function for the addition
print(np.add(x,y))
# ivison can also be performed using the divide function
print(np.divide(x,y))
print(np.sqrt(x))

Sum of the array is [[ 6  8]
 [10 12]]
Difference of two array is [[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 6  8]
 [10 12]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [74]:
# matrix Multiplication/Dot product

print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [75]:
# Multiplication of Vectors - Scalar
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])

print(a.dot(b))

30


In [76]:
print(a)

[1 2 3 4]


In [77]:
print(sum(a))

10


In [78]:
print(np.sum(a))

10


In [80]:
# we can also perform the sum on the basis of the axis

print(np.sum(x))
print(np.sum(x,axis=1))
# axis=1 is the sum along x direction
# axis=0 is the sum along the y direction

10
[3 7]


In [82]:
# Stacking of arrays
print(a)
b=b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [85]:
# stack functon basically use to join the two arrays
print(np.stack((a,b),axis=1))
print(np.stack((a,b),axis=0))

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]
[[ 1  2  3  4]
 [ 1  4  9 16]]


In [87]:
# rshape is the function that is basicaaly used to change the order of the arrays
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [89]:
# Now we are reshaping the 1-D to 3-D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [90]:
# Returns copy or view
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [91]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [93]:
# if we pass the value for the resphape equal to -1
# this will result in the flattening of the arrays
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [8]:
# Here we learn how to implement the function of the statics using the numpy libararay
a=np.array([[1,2,3,4],[5,0,7,8]])
print(a)
print(np.min(a))
# specific axis of direction in the case of multidimensional array
print(np.min(a,axis=0))
print(np.min(a,axis=1))
# for finding the maximum element in the array function is max
print(np.max(a))

[[1 2 3 4]
 [5 0 7 8]]
0
[1 0 3 4]
[1 0]
8


In [13]:
# function for finding the mean for the array
b=np.array([1,2,3,4,5])
print(np.mean(b))
print(np.mean(b,axis=0))
# print(np.mean(b,axis=1))

3.0
3.0


In [3]:
import numpy as np
c=np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [17]:
# Mean vs average is weighted
a=np.array([1,5,4,2,0])

# Mean vs Average is Weighted
print(np.mean(a))
w=np.array([1,2,3,4,5])
print(np.average(c,weights=w))
# but if we pass all the elements in the array equal to 1 then avg=mean


2.4
2.066666666666667


In [20]:
# Standard deviation
# Inbuilt function for the standard deviation
print(np.std(c))
# variance is the square of standard deviation
print(np.var(c))

1.854723699099141
3.4400000000000004


In [22]:
# arange function in the array
a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [7]:
# we can also import the random using
# import np.random as np
#t#his used to store the state of the random numbers
import numpy as np
np.random.seed(1)
a=np.array([1,5,4,2,0])
np.random.shuffle(a)
print(a)

[4 5 0 1 2]


In [33]:
# rand function create the array of random numbers
a=np.random.rand(2,3)
print(a)

[[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [34]:
# Returns values from a standard normal distribution
a=np.random.randn(2,3)
print(a)

[[-1.10593508 -1.65451545 -2.3634686 ]
 [ 1.13534535 -1.01701414  0.63736181]]


In [39]:
# it will print the random numbers between 5 to 10
a=np.random.randint(5,10,3)
print(a)

[6 8 5]


In [31]:
# Randoly pick the one element from the array
element=np.random.choice([1,4,3,2,11,27])
print(element)

27
